### ISSUE TITLE
highlighting tags

### ISSUE THREAD

**Issue by scotticles** [markov2/perl5-Apache-Solr#1]
First: thank you for providing this module, im migrating from webservices::solr due to it auto formatting my queries and i need more of a raw query builder.

I am trying to implement the highlighter but not a fan of the em tags.

I get this:
Bareword "hl" not allowed while "strict subs" in use ...
Bareword "tag" not allowed while "strict subs" in use ...

when trying to use 
`hl.tag.pre => '<p class="text-danger">', 'hl.tag.post' => '</p>'` on my select query.

Any thoughts, im wondering if its the Tables.pm that needs to be updated to allow these params?

**Comment by markov2** [comment]
* Scott (notifications@github.com) [190124 18:02]:
> I am trying to implement the highlighter but not a fan of the em tags.

Well, with CSS you can make <em>s display in any way you want...  Wrap it
in some container as selector.

> I get this:
> Bareword "hl" not allowed while "strict subs" in use ...
> Bareword "tag" not allowed while "strict subs" in use ...
> 
> when trying to use 
> `hl.tag.pre` => '<p class="text-danger">', 'hl.tag.post' => '</p>'` on my select query.

I have no set-up to test Solr at the moment.  So, please help me with
your exact code and error messages so I can debug it "dry".  Mail them
to me at perl@overmeer.net
-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by scotticles** [comment]
True, i might just do a css mod for em and call it good. I'll email you some snippets see if you can see anything obvious. I should mention my solr is on 7.0 version.

**Comment by scotticles** [comment]
Okay update: I was about to send the email but decided to look a little more at the solr docs, i had my hl wrong so it was  
`'hl.simple.pre' => '<p class="text-danger">', 'hl.simple.post' => '</p>' `
not hl.tag.pre, i must have read another doc on it that said tag. Its working now. Life is good :+1:
